### ISSUE TITLE
Chinese city names

### ISSUE THREAD

**Issue by dashinfantry** [a-dekker/worldclock#12]
How to give You Chinese translation?

**Comment by a-dekker** [comment]
I can think of multiple ways:

1. Create a fork on github, add the file CityTranslations-zh_CN.txt with the translations and create a pull request.
2. Just make a translation file and I will give you my email address so you can send it to me later.

**Comment by dashinfantry** [comment]
You can give me your email address

**Comment by a-dekker** [comment]
You should have received a message on openrepos.net about that.

**Comment by a-dekker** [comment]
Any progress on the city translations?

**Comment by a-dekker** [comment]
Changes released in v0.12-2
