### ISSUE TITLE
Chinese char of PM/AM overlapped the country time

### ISSUE THREAD

**Issue by TMavica** [a-dekker/worldclock#2]
![screenshot-22-04-15-02-27-47](https://cloud.githubusercontent.com/assets/1841472/7259667/6f7d4972-e897-11e4-8d7f-1e4a8f1c7b15.png)

**Comment by a-dekker** [comment]
I didn't really take localization into account. Now I noticed that German has even more overlap.
Maybe I should enforce English in every aspect to prevent this.

Thanks for reporting.

**Comment by a-dekker** [comment]
commit version 0.1-14 should save removed all localization of date/time related content, so all should be English-US. You could install the latest version from https://openrepos.net/content/ade/worldclock to check.
