### ISSUE TITLE
Reformat timezone list?

### ISSUE THREAD

**Issue by jansol** [a-dekker/worldclock#4]
Currently the list to choose timezones from is a cumbersome mess. Search is nice but not always an option (which one of those big cities along the west coast was used for naming the timezone again...). Therefore I'd like to propose a slightly more sophisticated sorting algorithm for the list:
- sort by continent
- per continent, sort by timezone
- per timezone, sort by city name

**Comment by a-dekker** [comment]
The sort is by continent/cityname, so it is not some random sort.
I think alternative sort are possible, but the issue remains that the city list if far from complete (you won't find San Francisco on the west coast).
I might have a look at it (and of course you can also make a pull request).

**Comment by a-dekker** [comment]
Added various sort options for the citylist, and also included country names.
In combination with the search option, you should be able to find the most suitable city.
